version: '3'

services:
  proxy:
    image: haproxy:1.7
    ports:
      - "90:80"
    volumes:
      - ./haproxy:/usr/local/etc/haproxy
  app1:
      image: results_provider:latest
  app2:
      image: results_provider:latest
  app3:
      image: results_provider:latest